In [4]:
'''
What is NumPy?
NumPy is a Python library for fast numerical computations using arrays and matrices.

Key Object:
ndarray – a multi-dimensional array used for storing data.

Why Use It?

Faster and more memory-efficient than Python lists

Easy mathematical operations

Essential for data science, ML, and scientific computing

Common Features:

Vectorized operations (no need for loops)

Broadcasting (auto-adjusts shapes in operations)

Built-in math functions: sum, mean, dot, etc.

'''

'\nWhat is NumPy?\nNumPy is a Python library for fast numerical computations using arrays and matrices.\n\nKey Object:\nndarray – a multi-dimensional array used for storing data.\n\nWhy Use It?\n\nFaster and more memory-efficient than Python lists\n\nEasy mathematical operations\n\nEssential for data science, ML, and scientific computing\n\nCommon Features:\n\nVectorized operations (no need for loops)\n\nBroadcasting (auto-adjusts shapes in operations)\n\nBuilt-in math functions: sum, mean, dot, etc.\n\n'

In [5]:
!pip install numpy

In [6]:
import numpy as np

#create arrays using numpy
#1d array

arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [7]:
#1d array
arr2 = np.array([1,2,3,4,5,6,7,8])
arr2.reshape(2,4) # 2 row , 4 colns 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
#2d array 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)

(3, 3)


In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
num = np.arange(0,10).reshape(5,2)

In [11]:
num

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
#create array using ones --> all one in array

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### Numpy Vectorized operations 

In [14]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

#addition 

print(arr1+arr2)

[ 7  9 11 13 15]


In [15]:
#subtraction 
print(arr1-arr2)

# multiplication
print(arr1*arr2)

#division 
print(arr1/arr2)

[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [16]:
#universal function 
arr = np.array([2,3,4,5,6])
#sq root 
print(np.sqrt(arr))
#exponential 
print(np.exp(arr))

#sine 
print(np.sin(arr))

#natural log 
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


##### array slicing and indexing 


In [17]:
arr = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))

print("Array : \n" , arr)


Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
print(arr[0])
print(arr[0][0])
print(arr[1][2])

[1 2 3 4]
1
7


In [19]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arr[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [21]:
print(arr[0:2])
print(arr[0:2 , 2:])

[[1 2 3 4]
 [5 6 7 8]]
[[3 4]
 [7 8]]


##### Modify array elements


In [22]:
arr[0][0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [23]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


##### statistical concepts --> Normalization

In [24]:
# to have a mean of 0 and stdard deviation of 1 

data = np.array([1,2,3,4,5])

#calcuate mean and standard deviation 
mean = np.mean(data)
std_dev = np.std(data)
print(f"Mean : {mean} and Standard deviation : {std_dev}")

Mean : 3.0 and Standard deviation : 1.4142135623730951


In [25]:
#normalized data 
normalized_data = (data-mean)/std_dev
print(f"Normalized data: {normalized_data}")

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [27]:
var = np.var(data)
print(f"Variance : {var}")

median = np.median(data)
print(f"Median: {median}")

Variance : 2.0
Median: 3.0


##### logical operations 

In [40]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data>=5)
print(data [(data>5) & (data<=8)])

[False False False False  True  True  True  True  True  True]
[6 7 8]
